version: '3.7'

services:
  zeebe: # https://docs.camunda.io/docs/self-managed/platform-deployment/docker/#zeebe
    image: "hauptmedia/zeebe-with-exporters:SNAPSHOT"
    ports:
      - "26500:26500"
      - "5701:5701"
    environment: # https://docs.camunda.io/docs/self-managed/zeebe-deployment/configuration/environment-variables/
      ZEEBE_LOG_LEVEL: debug
      SPRING_CONFIG_ADDITIONAL_LOCATION: /usr/local/zeebe/config/hazelcast-exporter.yml
      ZEEBE_HAZELCAST_FORMAT: json
    restart: always
    volumes:
      - zeebe:/usr/local/zeebe/data

  zbcat:
    restart: always
    image: node:16
    depends_on:
      - zeebe
    command: [ "npx", "@hauptmedia/zbcat@1.1.0", "--hazelcast", "--hazelcast-cluster-members", "zeebe:5701" ]


volumes:
  zeebe: