cloudevents:
  httpListener:
    host: "CLOUDEVENTS_HTTP_LISTENER_HOST"
    port: "CLOUDEVENTS_HTTP_LISTENER_PORT"

  httpSender:
    endpoint: "CLOUDEVENTS_HTTP_SENDER_ENDPOINT"

kafka:
  clientId: "KAFKA_CLIENT_ID"
  groupId: "KAFKA_GROUP_ID"
  topics:
    __name: "KAFKA_TOPICS"
    __format: json
  brokers:
    __name: "KAFKA_BROKERS"
    __format: json

hazelcast:
  ringbufferName: "HAZELCAST_RINGBUFFER_NAME"
  clusterName: "HAZELCAST_CLUSTER_NAME"
  clusterMembers:
     __name: "HAZELCAST_CLUSTER_MEMBERS"
     __format: json

zeebe:
  client:
    gatewayAddress: "ZEEBE_CLIENT_GATEWAY_ADDRESS"