cloudevents:
    httpListener:
      host: 0.0.0.0
      port: 8080
      allowHTTP1: true
      secure: false

    httpSender:
      source: kafka
      secure: true

kafka:
  clientId: zeebe-cloudevents-gateway
  groupId: zeebe-cloudevents-gateway
  topics:
    - zeebe
  brokers:
    - localhost:9092

zeebe:
  client:
    gatewayAddress: localhost:26500