cloudevents:
    consumer:
      httpServer:
        port: 7777
        host: 0.0.0.0
        allowHTTP1: true
    producer:
      httpSender:
        insecure: false
      kafkaConsumer:
        clientId: zeebe-cloudevents-gateway
        groupId: zeebe-cloudevents-gateway
        topics:
          - zeebe
        brokers:
          - localhost:9092
