cloudevents:
    httpListener:
      host: 0.0.0.0
      port: 8080
      allowHTTP1: true
      insecure: true

    httpSender:
      insecure: false
      source: kafka

kafka:
  clientId: zeebe-cloudevents-gateway
  groupId: zeebe-cloudevents-gateway
  topics:
    - zeebe
  brokers:
    - localhost:9092

zeebe:
  client:
    gatewayAddress: localhost:26500