cloudevents:
    producer:
      httpSender:
        insecure: false
      kafkaConsumer:
        clientId: zeebe-cloudevents-gateway
        groupId: zeebe-cloudevents-gateway
        topics:
          - zeebe
        brokers:
          - localhost:9092
