cloudevents:
    httpListener:
      port: 7777
      host: 0.0.0.0
      allowHTTP1: true

    httpSender:
      insecure: false
      endpoint: https://localhost:4000

consumer:
    kafka:
      clientId: zeebe-cloudevents-gateway
      groupId: zeebe-cloudevents-gateway
      topics:
        - zeebe
      brokers:
        - localhost:9092

zeebe:
  client:
    gatewayAddress: localhost:26500