cloudevents:
  httpSender:
    secure: false
    endpoint: https://localhost:4000
#   source: hazelcast

  httpListener:
    secure: true
    key: |
      -----BEGIN PRIVATE KEY-----
      MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDaL5RRzGGU/p3F
      OBi5jDPlVbtulocRFdEOtdk9BhID2R4PqGUMyp2K32wu9AnZtpFhtHXdje/20uh2
      QtPI8D6qJ2qa49xZYnrpaLABp4mA9bBo81x+dQP2/MMrgDCjbrwkH7x8OwVMv4Ey
      ZAKpKB3esw6KbMqrPD7S/8XOREX4Sh7jVArsSiWKXqfw8JBsC9cfRPTAfOUB9akn
      rEueUgK8kt2Q0w6iQVJ3Y+o7LTytSwYFd6Iob3L4wMF4cIZfg1g9gpmKG0Z4VAQr
      vA9M4erB4mTZh8opkNG/j8V39PY+CbabbclJJp2wOUJZSulXHebK9vc3dxIvDB1A
      SaFSLLVfAgMBAAECggEAEyVvt4ne2ktJnv/gM5AZEbvnObod2iL2+Hp+uLsqo4nO
      +ILHc0robkJS5P/nSWKa+V7zpOCKuTcizRXqLczfQuE4mqT6NiHNNWRJZavFBjsJ
      IvyQFkzAb1EY811JZ14VRno+eQxY17ZKaRibnyp1DJDb6svHMSWVQcDOI96b4UC+
      YJBLryE0yTWBfspqceLfHG8Lm9MBs9sICyjU/67SlikMh3KjvFBFK+9q+3hkd+KG
      osw+Z2XUS3dKXZO6IKx3s6NiWsz380V1WdaE3yYw8fzjgGj3Ms9PPojoMJCiL3V+
      5RnhNx2cNv2BEzLKbxnM0swblWU9S9aUb3wlEV2E4QKBgQDscXmXzv6qzmqeRk0X
      anFnISYD04u5InstkiJ0ytkQShmkRl0R+byyjgwyCXNQbca2a6pBUgLNB3tee+zk
      wsS+yL6WnkiQsiB/0jHACl2Ik5b41RwZNOUuWRWDrL+F9Udm+hL5xm4F57aYUJai
      ljLaxWb2zAg0Z/71bov+vXkazwKBgQDsO4QrpolQKQtJh+vuVOtdMbSjyeHVyf1y
      ig8yMLy62ZWMa7/2BxwsWBE2h6qGE34lE1SxHL8DRnHdGBvWeiFyxMxKlJsUIhq9
      UIJ88iqjm8MNxJEZtQmPdwews5/LLXxz7VmjnrpnPHtcajIiQcaX5xLPsu4wqL4s
      736q7UIgcQKBgDvzVbpJMMdMSTpSZu+d/J0CiaoEtHO/q23VlMj6OelocHH3qVeK
      c+7uF2eEf+mPvAe66tNfIPitgflmAJ3MSKh7K9/yyEFv+M+QEy83MZoUmf4Dwvkd
      MVL8IXlejr0/gNg6Zh9Q0crLgr/CBz+4R7KyxLWk7Bullr7SRcrUbeV/AoGAZCNy
      iqJk0MMlUr04aOY8g1vfrBKXFe4y7svRV0BLsJUtjMHcNKmc6rtGSKxHv+AheAvy
      ucVqvzOsbsGag1dwOFtuEitedbFjTl8DgX2ST5pmm754l8IjVFprux7ZnOIiQG4b
      sn1FnR+JV4p4yAbD7X55fevmhl/xhdDcDA7ZGjECgYBzEuHBCbWDOpISWNPGmOab
      jXMA76ZBv1YSbk9UDGoFtTYtOiogLKL+TukTtcP60ZgaLkfBxwflB4kdmfDXLjUG
      ez2Zg1gVn8jBn23cfxG8u48fKqQXDcQ8/keAbL7MZe6739hePMXh74mOXB0huloC
      IgTfRNqT2DR4V3u/Jo9nLA==
      -----END PRIVATE KEY-----
    cert: |
      -----BEGIN CERTIFICATE-----
      MIIDCTCCAfGgAwIBAgIUaJbM3yFBH9CrNKP7X1vmEh4OKsEwDQYJKoZIhvcNAQEL
      BQAwFDESMBAGA1UEAwwJbG9jYWxob3N0MB4XDTIyMTEyODE4NDIwOFoXDTIyMTIy
      ODE4NDIwOFowFDESMBAGA1UEAwwJbG9jYWxob3N0MIIBIjANBgkqhkiG9w0BAQEF
      AAOCAQ8AMIIBCgKCAQEA2i+UUcxhlP6dxTgYuYwz5VW7bpaHERXRDrXZPQYSA9ke
      D6hlDMqdit9sLvQJ2baRYbR13Y3v9tLodkLTyPA+qidqmuPcWWJ66WiwAaeJgPWw
      aPNcfnUD9vzDK4Awo268JB+8fDsFTL+BMmQCqSgd3rMOimzKqzw+0v/FzkRF+Eoe
      41QK7Eolil6n8PCQbAvXH0T0wHzlAfWpJ6xLnlICvJLdkNMOokFSd2PqOy08rUsG
      BXeiKG9y+MDBeHCGX4NYPYKZihtGeFQEK7wPTOHqweJk2YfKKZDRv4/Fd/T2Pgm2
      m23JSSadsDlCWUrpVx3myvb3N3cSLwwdQEmhUiy1XwIDAQABo1MwUTAdBgNVHQ4E
      FgQUZVfCYC5bsLlvyCJHVy1+H1D391QwHwYDVR0jBBgwFoAUZVfCYC5bsLlvyCJH
      Vy1+H1D391QwDwYDVR0TAQH/BAUwAwEB/zANBgkqhkiG9w0BAQsFAAOCAQEATSn8
      d6OaLc/b6BWSFJuaqHiVDQLZWG6UhVq56VbOiSTeYMJpT0RIOHFVB1MPjQsSapuZ
      Bpt84Fw3AZggAYtmvTzUfVToMYzwbPt/y55LWZ1ZywBSvB/yJXxcUkL+7wuN3HVN
      sXtf5LNcJHveRk07PD0KW91T8kRt1Bn39kjo6oXD8vCkMaFWpHz3eKry/1KpowgW
      ix7kGdbSnpcp9yLTaWLUX7DJCjM+jSIZuhH1XF65q47mZA+Rayhxu5+OTl71094U
      AyuxGdY/3Xk/6ryHyQt02w+qZtpz7GEO9CzTgIhKOc2bXJccZ+CixDL5cES1gwmS
      oWmV/hO0XK5q+XfaIA==
      -----END CERTIFICATE-----

hazelcast:
  ringbufferName: zeebe
  clusterName: dev
  clusterMembers:
    - localhost:5701
